-- Enable RLS (Row Level Security) is recommended but for simplicity we will just create tables first.
-- You can run this in Supabase SQL Editor

-- 1. Hero Section
CREATE TABLE IF NOT EXISTS hero_sections (
    id BIGINT PRIMARY KEY DEFAULT 1,
    greeting TEXT DEFAULT 'Hello, I''m',
    name TEXT DEFAULT 'Your Name',
    role TEXT DEFAULT 'Full Stack Developer',
    status_text TEXT DEFAULT 'Available for work',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS social_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    url TEXT NOT NULL,
    icon TEXT NOT NULL, -- Lucide icon name
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. About Section
CREATE TABLE IF NOT EXISTS about_sections (
    id BIGINT PRIMARY KEY DEFAULT 1,
    title TEXT DEFAULT 'About Me',
    description_1 TEXT,
    description_2 TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS about_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    value TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    issuer TEXT NOT NULL,
    date TEXT, -- e.g. "2025"
    logo_url TEXT,
    cert_image_url TEXT, -- For PDF/Image preview
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Video Section
CREATE TABLE IF NOT EXISTS video_sections (
    id BIGINT PRIMARY KEY DEFAULT 1,
    subtitle TEXT DEFAULT 'My Process',
    description TEXT,
    video_url TEXT,
    cover_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- 4. Contact Items (Refactor form fixed fields)
CREATE TABLE IF NOT EXISTS contact_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT, -- e.g. "Email"
    value TEXT NOT NULL, -- e.g. "hello@example.com"
    icon TEXT NOT NULL, -- Lucide icon name
    type TEXT, -- 'email', 'phone', 'location', 'line', etc.
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Update Projects Table (Add long description for Modal)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS long_description TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS duration TEXT;

-- Initial Seed for Single Row Tables (Upsert)
INSERT INTO hero_sections (id, greeting, name, role, status_text)
VALUES (1, 'Hello, I''m', 'Natee Karni', 'Full Stack Developer', 'Available for work')
ON CONFLICT (id) DO NOTHING;

INSERT INTO about_sections (id, title, description_1, description_2)
VALUES (1, 'About Me', 'I am a passionate developer...', 'Specializing in...')
ON CONFLICT (id) DO NOTHING;

INSERT INTO video_sections (id, subtitle, description)
VALUES (1, 'Behind the Code', 'A glimpse into my development process...')
ON CONFLICT (id) DO NOTHING;
