-- Comprehensive Database Schema for Portfolio
-- Run this script in the Supabase SQL Editor to verify/update your database structure.

-- Enable Row Level Security (RLS) policies to allow public read access
-- NOTE: We use "IF NOT EXISTS" to make this script safe to re-run.

-----------------------------------------------------------------------------
-- 1. Hero Section
-----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hero_sections (
    id BIGINT PRIMARY KEY DEFAULT 1,
    greeting TEXT DEFAULT 'Hello, I''m',
    name TEXT DEFAULT 'Your Name',
    role TEXT DEFAULT 'Full Stack Developer',
    status_text TEXT DEFAULT 'Available for work',
    hero_image_url TEXT,
    hero_video_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- RLS: Enable and allow public read
ALTER TABLE hero_sections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Hero" ON hero_sections;
CREATE POLICY "Public Read Hero" ON hero_sections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Hero" ON hero_sections;
CREATE POLICY "Admin All Hero" ON hero_sections FOR ALL USING (true); -- Ideally restrict to authenticated users

-- Social Links
CREATE TABLE IF NOT EXISTS social_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    url TEXT NOT NULL,
    icon TEXT NOT NULL, -- Lucide icon name
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE social_links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Social" ON social_links;
CREATE POLICY "Public Read Social" ON social_links FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Social" ON social_links;
CREATE POLICY "Admin All Social" ON social_links FOR ALL USING (true);

-----------------------------------------------------------------------------
-- 2. About Section
-----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS about_sections (
    id BIGINT PRIMARY KEY DEFAULT 1,
    title TEXT DEFAULT 'About Me',
    description_1 TEXT,
    description_2 TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

ALTER TABLE about_sections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read About" ON about_sections;
CREATE POLICY "Public Read About" ON about_sections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All About" ON about_sections;
CREATE POLICY "Admin All About" ON about_sections FOR ALL USING (true);

-- Stats
CREATE TABLE IF NOT EXISTS about_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    value TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE about_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Stats" ON about_stats;
CREATE POLICY "Public Read Stats" ON about_stats FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Stats" ON about_stats;
CREATE POLICY "Admin All Stats" ON about_stats FOR ALL USING (true);

-- Certifications
CREATE TABLE IF NOT EXISTS certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    issuer TEXT NOT NULL,
    date TEXT,
    logo_url TEXT,
    cert_image_url TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE certifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Certs" ON certifications;
CREATE POLICY "Public Read Certs" ON certifications FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Certs" ON certifications;
CREATE POLICY "Admin All Certs" ON certifications FOR ALL USING (true);

-----------------------------------------------------------------------------
-- 3. Video Section
-----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS video_sections (
    id BIGINT PRIMARY KEY DEFAULT 1,
    subtitle TEXT DEFAULT 'My Process',
    description TEXT,
    video_url TEXT,
    cover_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

ALTER TABLE video_sections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Video" ON video_sections;
CREATE POLICY "Public Read Video" ON video_sections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Video" ON video_sections;
CREATE POLICY "Admin All Video" ON video_sections FOR ALL USING (true);

-----------------------------------------------------------------------------
-- 4. Contact Section
-----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    value TEXT NOT NULL,
    icon TEXT NOT NULL,
    type TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE contact_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Contact Items" ON contact_items;
CREATE POLICY "Public Read Contact Items" ON contact_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Contact Items" ON contact_items;
CREATE POLICY "Admin All Contact Items" ON contact_items FOR ALL USING (true);

-----------------------------------------------------------------------------
-- 5. Projects
-----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image TEXT, -- Main image URL
    tags JSONB DEFAULT '[]'::jsonb, -- Array of strings
    category TEXT DEFAULT 'Full Stack',
    github_url TEXT,
    demo_url TEXT,
    long_description TEXT,
    client_name TEXT,
    duration TEXT,
    is_featured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Projects" ON projects;
CREATE POLICY "Public Read Projects" ON projects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Projects" ON projects;
CREATE POLICY "Admin All Projects" ON projects FOR ALL USING (true);

-- Ensure columns exist (if table existed before without these)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS long_description TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS duration TEXT;

-----------------------------------------------------------------------------
-- 6. Services
-----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    icon TEXT DEFAULT 'Globe',
    category TEXT DEFAULT 'main',
    items JSONB DEFAULT '[]'::jsonb,
    gallery JSONB DEFAULT '[]'::jsonb,
    pricing JSONB DEFAULT '[]'::jsonb,
    is_active BOOLEAN DEFAULT TRUE,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE services ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Services" ON services;
CREATE POLICY "Public Read Services" ON services FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Services" ON services;
CREATE POLICY "Admin All Services" ON services FOR ALL USING (true);

-----------------------------------------------------------------------------
-- 7. Section Configurations (Headers/Descriptions)
-----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_sections (
    id BIGINT PRIMARY KEY DEFAULT 1,
    title TEXT DEFAULT 'Contact Me',
    description TEXT DEFAULT 'Get in touch',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

ALTER TABLE contact_sections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Contact Config" ON contact_sections;
CREATE POLICY "Public Read Contact Config" ON contact_sections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Contact Config" ON contact_sections;
CREATE POLICY "Admin All Contact Config" ON contact_sections FOR ALL USING (true);

CREATE TABLE IF NOT EXISTS services_sections (
    id BIGINT PRIMARY KEY DEFAULT 1,
    title TEXT DEFAULT 'My Services',
    description TEXT DEFAULT 'What I offer',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

ALTER TABLE services_sections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Services Config" ON services_sections;
CREATE POLICY "Public Read Services Config" ON services_sections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Services Config" ON services_sections;
CREATE POLICY "Admin All Services Config" ON services_sections FOR ALL USING (true);

CREATE TABLE IF NOT EXISTS projects_sections (
    id BIGINT PRIMARY KEY DEFAULT 1,
    title TEXT DEFAULT 'Featured Projects',
    description TEXT DEFAULT 'Some of my best work',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

ALTER TABLE projects_sections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Projects Config" ON projects_sections;
CREATE POLICY "Public Read Projects Config" ON projects_sections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Projects Config" ON projects_sections;
CREATE POLICY "Admin All Projects Config" ON projects_sections FOR ALL USING (true);

-----------------------------------------------------------------------------
-- 8. Messages (Contact Form)
-----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Create Messages" ON messages;
CREATE POLICY "Public Create Messages" ON messages FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Admin All Messages" ON messages;
CREATE POLICY "Admin All Messages" ON messages FOR ALL USING (true);

-----------------------------------------------------------------------------
-- Initial Seed Data (Upsert to ensure single row tables have data)
-- Note: We use ON CONFLICT DO NOTHING to preserve existing data if run again
-----------------------------------------------------------------------------

INSERT INTO hero_sections (id, greeting, name, role, status_text)
VALUES (1, 'Hello, I''m', 'Natee Karni', 'Full Stack Developer', 'Available for work')
ON CONFLICT (id) DO NOTHING;

INSERT INTO about_sections (id, title, description_1, description_2)
VALUES (1, 'About Me', 'I am a passionate developer...', 'Specializing in building exceptional digital experiences.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO video_sections (id, subtitle, description)
VALUES (1, 'Behind the Code', 'A glimpse into my development process and problem-solving approach.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO contact_sections (id, title, description)
VALUES (1, 'Contact Me', 'Get in touch')
ON CONFLICT (id) DO NOTHING;

INSERT INTO services_sections (id, title, description)
VALUES (1, 'My Services', 'What I offer')
ON CONFLICT (id) DO NOTHING;

INSERT INTO projects_sections (id, title, description)
VALUES (1, 'Featured Projects', 'Some of my best work')
ON CONFLICT (id) DO NOTHING;

-- Done!
